name: mongo_document_db_driver
version: 2.1.0
description: MongoDB driver for Dart, backed by MongoDB's official Rust driver. CRUD, aggregation, and more.
homepage: https://github.com/wanclem/mongo_document
repository: https://github.com/wanclem/mongo_document
issue_tracker: https://github.com/wanclem/mongo_document/issues
documentation: https://github.com/wanclem/mongo_document/tree/main/packages/mongo_document_db_driver

environment:
  sdk: ">=3.10.0 <4.0.0"

resolution: workspace

dependencies:
  bson: ^5.0.0
  code_assets: ^1.0.0
  crypto: ^3.0.0
  ffi: ^2.1.4
  fixnum: ^1.1.0
  hooks: ^1.0.2
  logging: ^1.0.0
  mongo_dart_query: ^5.0.1
  collection: ^1.15.0
  path: ^1.8.0
  pool: ^1.5.0
  basic_utils: ^5.2.0
  decimal: ^3.1.0
  uuid: ^4.0.0
  sasl_scram: ^0.1.0
  vy_string_utils: ^0.4.0
    
dev_dependencies:
  test: ^1.16.4
  lints: ^6.0.0

false_secrets:
 - /test/certificates_for_testing/*.key
 - /test/certificates_for_testing/*.pem
